dashboard/urls.py
from django.conf.urls import patterns, url, include
from . import views

urlpatterns = patterns('',
    url(r'^$', views.main_panel, name='main_panel'),
    url(r'^notifications/$', views.notifications, name='notifications'),
    url(r'^notifications/(?P<pk>\d+)/$', views.notification_link, name='notification_link'),
    )

travel/urls.py
from django.conf.urls import patterns, url
from . import views

urlpatterns = patterns('',
    url(r'^$', views.travel_list, name='travel_list'),
    url(r'^(?P<pk>\d+)/$', views.travel_detail, name='travel_detail'),

    url(r'^(?P<pk>\d+)/subscribe$', views.travel_subscribe, name='travel_subscribe'),
    url(r'^(?P<pk>\d+)/unsubscribe$', views.travel_unsubscribe, name='travel_unsubscribe'),
    url(r'^mytravels/$', views.my_travels, name='my_travels'),
    url(r'^mycreatedtravels/$', views.my_created_travels, name='my_created_travels'),
    url(r'^create/$', views.create_travel, name='create_travel')
)

wu/urls.py
from django.conf.urls import patterns, url
from . import views

urlpatterns = patterns('',
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^profile/$', views.user_profile, name='profile'),
    url(r'^update_profile/$', views.user_profile_update, name='update_profile'),
    url(r'^family/$', views.user_list, name='user_list'),
    url(r'^family/(?P<pk>\d+)/$', views.user_detail, name='user_detail'),
)

wup/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^$', 'wu.views.index'),
    url(r'^index.html$', 'wu.views.index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('wu.urls', namespace='users')),
    url(r'^dashboard/', include('dashboard.urls', namespace='main')),
    url(r'^travel/', include('travel.urls', namespace='travel')),
]

#autorisaton to access static and media file. In prod environement this may be changed by http server rules 
urlpatterns += [
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.STATIC_ROOT,
    })]

travel/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils import timezone
from django.core.validators import MaxValueValidator


class Travel(models.Model):
    author = models.ForeignKey('wu.WuProfil')
    title = models.CharField(max_length=200)
    description = models.TextField(max_length=2000)
    created_date = models.DateTimeField(default=timezone.now)
    starting_date = models.DateField(blank=True, null=True)
    ending_date = models.DateField(blank=True, null=True)
    participants = models.ManyToManyField('wu.WuProfil', through='Participate',
                                          through_fields=('travel', 'person'), related_name='manytomany_user',
                                          blank=True)
    image = models.ImageField(blank=True, upload_to='images', default='images/road-trip.jpg')
    budget = models.PositiveSmallIntegerField(blank=True, help_text='Bugdet prévisionnel par personne pour le voyage entier',
                                              validators=[MaxValueValidator(limit_value=1000)])

    def __str__(self):
        return self.title+" - "+str(self.created_date)


class Participate(models.Model):
    person = models.ForeignKey('wu.WuProfil')
    travel = models.ForeignKey('travel')
    motivation = models.PositiveSmallIntegerField()

    def __str__(self):
        return str(self.person)


class Stage(models.Model):
    travel = models.ForeignKey(Travel, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    point_of_departure = models.CharField(max_length=300)
    point_of_arrival = models.CharField(max_length=300)
    duration = models.PositiveSmallIntegerField(default=1, blank=True, help_text='Durée en jours pour l\'étape',
                                                validators=[MaxValueValidator(limit_value=21)])
    description = models.TextField(blank=True,max_length=2000)

travel/forms.py
# -*- coding: utf-8 -*-
from django import forms
from .models import Travel, Stage
from django.forms import inlineformset_factory

MAX_STAGES = 30

StageFormSet = inlineformset_factory(
    Travel,
    Stage,
    extra=1,
    min_num=0,
    max_num=MAX_STAGES,
    fields=('title', 'point_of_departure', 'point_of_arrival', 'duration', 'description'))


class TravelForm(forms.ModelForm):
    title = forms.CharField(max_length=200, label='Titre du Voyage')
    description = forms.CharField(widget=forms.Textarea, max_length=2000, help_text="Description du voyage", label='Description du voyage')
    starting_date = forms.DateField(label='Date de début')
    ending_date = forms.DateField(label='Date de fin')
    image = forms.ImageField(label='Image associée : ')
    budget = forms.IntegerField(help_text='(par personne pour le voyage entier)', min_value=0,
                                max_value=1500, label='Bugdet prévisionnel')

    class Meta:
        model = Travel
        fields = ('title', 'description', 'starting_date', 'ending_date', 'budget', 'image')


class StageForm(forms.ModelForm):
    title = forms.CharField(max_length=200, label='Nom de l\'étape')
    point_of_departure = forms.CharField(max_length=300, label='Point de départ')
    point_of_arrival = forms.CharField(max_length=300, label='Point d\'arrivée')
    duration = forms.IntegerField(help_text='(en jours)', max_value=21, min_value=0, label='Durée')
    description = forms.CharField(widget=forms.Textarea, max_length=2000, label='')

    class Meta:
        model = Stage
        fields = ('title', 'point_of_departure', 'point_of_arrival', 'duration', 'description')

travel/views.py
# -*- coding: utf-8 -*-

from django.shortcuts import render, get_object_or_404, redirect,render_to_response
from django.template import RequestContext
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from .models import Travel
from wu.models import WuProfil
from .forms import TravelForm, StageFormSet
from .models import Stage
from .models import Participate
from dashboard.models import Historique
from django.views.generic import CreateView, UpdateView


@login_required
def travel_list(request):
    travels = Travel.objects.order_by('-created_date')
    return render(request, 'travel/travel_list.html', {'title':'Liste des voyages', 'travels': travels})


@login_required
def my_created_travels(request):
    travels = Travel.objects.filter(author__user=request.user.id).order_by('created_date')
    return render(request, 'travel/travel_list.html', {'title':'Mes voyages créés', 'travels': travels})


@login_required
def my_travels(request):
    travels = Travel.objects.filter(id__in=[participate.travel.id for participate in Participate.objects.filter(person__user=request.user.id)]).order_by('created_date')
    return render(request, 'travel/travel_list.html', {'title':'Mes voyages', 'travels': travels})


@login_required
def travel_detail(request, pk, message=""):
    travel = get_object_or_404(Travel, pk=pk)
    stages = Stage.objects.filter(travel=travel.id)
    participants = travel.participants.all()
    participating = False
    if len(travel.participants.filter(user=request.user.id)) > 0:
        participating = True
    return render(request, 'travel/travel_detail.html', {'message':message, 'travel': travel, 'stages':stages, 'participants':participants, 'participating':participating})

@login_required
def travel_subscribe(request, pk):
    travel = get_object_or_404(Travel, pk=pk)
    if len(travel.participants.filter(user_id=request.user.id)) < 1:
        participation=Participate(person=request.user.wuprofil, travel=travel, motivation=5)
        participation.save()

        Historique.newTravelFact(
            actor=request.user.wuprofil,
            action_type="TS",
            object_travel=travel
        )


    return HttpResponseRedirect('/travel/%s/' % pk)


@login_required
def travel_unsubscribe(request, pk):
    travel = get_object_or_404(Travel, pk=pk)
    participations=Participate.objects.filter(person__user__id=request.user.id, travel_id=pk)
    if len(participations) > 0:
        for participation in participations:
            participation.delete()

        Historique.newTravelFact(
            actor=request.user.wuprofil,
            action_type="TU",
            object_travel=travel
        )


    return HttpResponseRedirect('/travel/%s/' % pk)

'''
@login_required
def create_travel(request):
    if request.method == 'POST':
        form = TravelForm(request.POST, request.FILES)

        if form.is_valid():
            print("Form valid")
            travel = form.save(commit=False)
            wu_user = WuProfil.objects.get(user=request.user)
            travel.author = wu_user
            travel.save()
            form.save_m2m()
            return travel_list(request)
        else:
            # The supplied form contained errors - just print them to the terminal.
            print("form invalid")
            print(form.errors)
    else:
        # If the request was not a POST, display the form to enter details.
        form = TravelForm()

    # Bad form (or form details), no form supplied...
    # Render the form with error messages (if any).
    return render(request, 'travel/add_travel.html', {'form': form})
'''


@login_required
def create_travel(request):
    if request.POST:
        form = TravelForm(request.POST, request.FILES)

        if form.is_valid():
            print("Form valid")
            travel = form.save(commit=False)
            wu_user = WuProfil.objects.get(user=request.user)
            travel.author = wu_user
            stage_formset = StageFormSet(request.POST, instance=travel)
            if stage_formset.is_valid():
                travel.save()
                stage_formset.save()
                form.save_m2m()

                Historique.newTravelFact(
                    actor=request.user.wuprofil, 
                    action_type="TC",
                    object_travel=travel
                )

                return travel_list(request)
            else :
                print("Stage formset invalid")
                print(form.errors)
        else :
            print("Travel formset invalid")
            print(form.errors)
    else:
        form = TravelForm()
        stage_formset = StageFormSet(instance=Travel())

    return render(request, "travel/add_travel.html", {"form": form, "stage_formset": stage_formset})

travel/templates/travel/add_travel.html
{% extends "base.html" %}

{% load bootstrap %}
{% block content %}

<div class="container">
     <form action="." method="post" class="travel_form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|bootstrap }}
        {{ stage_formset|bootstrap }}
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Créer</button>
        </div>
  </form>
</div>


{% endblock content %}

travel/templates/travel/travel_detail.html
{% extends 'base.html' %}

{% block content %}

     <div class="container">
      <div class="starter-template">
       <div class="publication row">

         <div style="padding-top:20px" class="btn-group" role="group">
          <a href="javascript:history.back()"><button class="dashboard-action-button btn btn-medium btn-default">Retour</button></a>
          {% if participating == False %}
          <a href="subscribe"><button type="button" class="btn btn-success">Participer</button></a>
          {% else %}
          <a href="unsubscribe"><button type="button" class="btn btn-warning">Abandonner</button></a>
          {% endif %}
          <quote style="padding-left:20px;color:red;"> {{ message }}</quote>
       	</div>
		<div class="col-lg-8">


			<div class="row publication-header">
                <table>
                  <tr>
                    <td>
                      <img class="publication-header-logo " src="{{ travel.author.image.url }}">
                    </td>
                    <td>
                      <div class="publication-header-announce "> <p>par <b>{{ travel.author.user.username }}</b><br/>
                     Publié le {{ travel.created_date }}</div><!---->
                    </td>
                  </tr>
                </table>
              </div>
            <div class="row publication-content">
              <div class="publication-content-title publication-content-detailed"> <h2>{{ travel.title }}</h2></div> 
              <table>
                <tr>
                  <td>
                    <div> 
                      <img class="publication-content-image"  src="{{ travel.image.url }}" /> 
                      <p class="publication-content-text"> {{ travel.description }}</p>
                    </div>
                  </td>
                </tr>
                <tr>
                  <td>
                    <div>
                     <h3 class="details"><b>Les étapes</b></h3>
                     <div class="publication-stages"> 
                     	<ul class="list-group">
               				  {% for stage in stages %}
                       			<li class="list-group-item add-vertical-space">
                              <p><h4><b><u class="add-vertical-space">{{ stage.title }}</u></b></h4></p>
                              <p><i>{{ stage.description }}</i></p>
                              </br>
                              <p><u>Départ</u> : {{ stage.point_of_departure }}</p>
                              <p><u>Arrivée</u> : {{ stage.point_of_arrival }}</p>
                              <p><u>Durée en jour(s)</u> : {{ stage.duration }}</p>
                            </li>
                  			{% endfor %}
                     	</ul>
                     </div>
                    </div>
                  </td>
                </tr>
                 <tr>
                  <td>
                    <div class="participants">
                       <h3 class="details"><b>Participants</b></h3>
                       <div class="row sub-content"> 
                          {% for participant in participants %}
                              <div class="col-lg-2">
                                <table>
                                  <tr>
                                    <td>
                                      <img class="publication-participant-logo " src="{{ participant.image.url }}">
                                    </td>
                                    <td>
                                      <div class="publication-participant-name ">{{ participant.user.username }}</b><br/></div><!---->
                                    </td>
                                    <td>
                                      <div class="publication-participant-name ">{{ participant.motivation }}/5</b><br/></div><!---->
                                    </td>
                                  </tr>
                                </table>
                              </div>
                          {% endfor %}
                       </div>
                    </div>
                  </td>
                </tr>
              </table>
            </div>
          </div>
      </div>
      </div>
      </div>
{% endblock %}

travel/templates/travel/travel_list.html
{% extends 'base.html' %}

{% block content %}



<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{% url 'travel:travel_list' %}">Voyages</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse ">
    <ul class="nav navbar-nav">
     
          <li><a href="{% url 'travel:create_travel' %}">Proposer un voyage</a></li>
          <li><a href="{% url 'travel:my_created_travels' %}">Mes voyages créés</a></li>
          <li><a href="{% url 'travel:my_travels' %}">Voyages auxquels je participe</a></li>
          <li><a href="{% url 'main:main_panel' %}">Retour au menu</a></li>
    </ul>
    <!--<form class="navbar-form navbar-left" role="search">
      <div class="form-group">
        <input class="form-control" placeholder="..." type="text">
      </div>
      <button type="submit" class="btn btn-default">Chercher</button>

    </form>-->
    
  </div><!-- /.navbar-collapse -->
</nav>
     <div class="container">


      <div class="starter-template">

        <h1>{{ title }}</h1>

       <div class="publication row">
      
       {% for travel in travels %}
          <div class="col-lg-8">
              <div class="row publication-header">
                <table>
                  <tr>
                    <td>
                      <img class="publication-header-logo " src="{{ travel.author.image.url }}">
                    </td>
                    <td>
                      <div class="publication-header-announce "> <p>créé par <b>{{ travel.author.user.username }}</b><br/>
                     Publié le {{ travel.created_date }}</div><!---->
                    </td>
                  </tr>
                </table>
              </div>
            <div class="row publication-content">
              <div class="publication-content-title"> <h4>{{ travel.title }}</h4></div> 
              
              <div> 
                <img class="publication-content-image"  src="{{ travel.image.url }}" /> 
                <p class="publication-content-text"> {{ travel.description }}</p>
               </div>
                <a href="/travel/{{ travel.id }}"><button type="button" class="btn btn-default">Détails..</button></a>
            </div>
          </div>
           {% endfor %}
        </div>
      </div>
    </div><!-- /.container -->

{% endblock content %}