dashboard/urls.py
from django.conf.urls import patterns, url, include
from . import views

urlpatterns = patterns('',
    url(r'^$', views.main_panel, name='main_panel'),
    url(r'^notifications/$', views.notifications, name='notifications'),
    url(r'^notifications/(?P<pk>\d+)/$', views.notification_link, name='notification_link'),
    )

wu/urls.py
from django.conf.urls import patterns, url
from . import views

urlpatterns = patterns('',
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^profile/$', views.user_profile, name='profile'),
    url(r'^update_profile/$', views.user_profile_update, name='update_profile'),
    url(r'^family/$', views.user_list, name='user_list'),
    url(r'^family/(?P<pk>\d+)/$', views.user_detail, name='user_detail'),
)

wup/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^$', 'wu.views.index'),
    url(r'^index.html$', 'wu.views.index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('wu.urls', namespace='users')),
    url(r'^dashboard/', include('dashboard.urls', namespace='main')),
    url(r'^travel/', include('travel.urls', namespace='travel')),
]

#autorisaton to access static and media file. In prod environement this may be changed by http server rules 
urlpatterns += [
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.STATIC_ROOT,
    })]

wu/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator


class WuProfil(models.Model):
    user = models.OneToOneField(User)
    promo = models.PositiveSmallIntegerField(help_text='L\'année de fin du cursus INSA',
                                             validators=[MaxValueValidator(limit_value=2050),
                                                         MinValueValidator(limit_value=2014)])
    city = models.CharField(blank=True,max_length=150, help_text='Ville actuelle')
    can_welcome_people = models.BooleanField(default=False, blank=True,
                                             help_text='Possibilité d\'accueillir des WUs en transit')
    image = models.ImageField(upload_to='profile_images', default='profile_images/nobody.jpg')

    def __str__(self):
        return self.user.username

wu/forms.py
from django import forms
from .models import WuProfil
from django.contrib.auth.models import User


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'email', 'password', 'first_name', 'last_name']


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = WuProfil
        fields = ['promo', 'city', 'can_welcome_people', 'image']

wu/views.py
from django.shortcuts import render, HttpResponse, HttpResponseRedirect, redirect, get_object_or_404
from .forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import logout_then_login
from .models import WuProfil
from django.contrib.auth.models import User
from wup import settings
from dashboard.models import Historique

def index(request):
    if not request.user.is_authenticated():
        return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))
    else:
        return redirect('/dashboard')


def register(request):

    # Used later if registration is valid
    registered = False

    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # create regular user in database + set password
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            # commit= false delays the transaction for WuProfil
            profile = profile_form.save(commit=False)
            profile.user = user

            if 'image' in request.FILES:
                profile.image = request.FILES['image']

            # Now we save the UserProfile model instance.
            profile.save()

            # Update our variable to tell the template registration was successful.
            registered = True

            Historique.newUserFact(
                actor=user.wuprofil, 
                action_type="UJ",
                object_user=user.wuprofil
            )

        # Invalid form or forms - mistakes or something else?
        # Print problems to the terminal.
        # They'll also be shown to the user.
        else:
            print(user_form.errors, profile_form.errors)

    # Not a HTTP POST, so we render our form using two ModelForm instances.
    # These forms will be blank, ready for user input.
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    # Render the template depending on the context.
    return render(request,
            'wu/register.html',
            {'user_form': user_form, 'profile_form': profile_form, 'registered': registered})


def user_login(request):
    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)

        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.
        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                return HttpResponseRedirect('/dashboard/')
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your WUP account is disabled.")
        else:
            # Bad login details were provided. So we can't log the user in.
            print("Invalid login details: {0}, {1}".format(username, password))
            return HttpResponse("Invalid login details supplied.")

    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render(request, 'wu/login.html', {})


def user_logout(request):
        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.
        username = request.user.username
        return logout_then_login(request, '/users/login', {'username': username})


def user_profile(request):
    wu_user = get_object_or_404(WuProfil, user=request.user)
    return render(request, 'wu/profile.html', { 'user': request.user, 'wu_user': wu_user })

# problem here !
def user_list(request):
    current_user = request.user
    users = User.objects.exclude(id__exact=current_user.id)
    wu_users = WuProfil.objects.exclude(id__exact=current_user.id)
    all_users = zip(users, wu_users)
    return render(request, 'wu/wu_list.html', {'all_users': all_users})

def user_detail(request, pk):
    user = get_object_or_404(User, pk=pk)
    wu_user = WuProfil.objects.get(user = user)
    return render(request, 'wu/wu_detail.html', {'user': user, 'wu_user': wu_user})

def user_profile_update(request):
    #wu_user = get_object_or_404(WuProfil, user=request.user)
    return render(request, 'wu/profile_update.html')

wu/templates/wu/login.html
{% extends 'base.html' %}


{% block content %}

        <!--<form id="login_form" method="post" action="/users/login/">
            
            Username: <input type="text" name="username" value="" size="50" />
            <br />
            Password: <input type="password" name="password" value="" size="50" />
            <br />

            <input type="submit" value="submit" />
        </form>-->
        <div class="loginmodal-container" action="/users/login/">
        <h1>Connecte-toi avec tes identifiants</h1><br>
            <form method="POST">
            	{% csrf_token %}
            <input type="text" name="username" placeholder="Identifiant" size="50">
            <input type="password" name="password" placeholder="Mot de passe" size="50">
            <input type="submit" name="login" class="login loginmodal-submit" value="Login">
            </form>
             <!-- <a href="/users/register">S'inscrire</a>-->
            
          <div class="login-help">
            <a href="/users/register">Register</a> - <a href="#">Forgot Password</a>
            </div>
          </div>

{% endblock content %}

wu/templates/wu/logout.html
{% extends 'base.html' %}

{% block content %}

        <h1>Au revoir {{ username }}</h1>

{% endblock content %}

wu/templates/wu/profile.html
{% extends 'base.html' %}

{% block content %}
<div class='formulaire-part' >
    <h1>Profil utilisateur de {{ user.username }}</h1>
    <h2>Vos informations :</h2>
    <img style='width:50%' class="add-vertical-space" src="{{ wu_user.image.url }}">
    <p>Date d'inscription sur le site  : {{ user.date_joined}} </p>
    <p>Nom : {{ user.last_name }}, Prénom : {{ user.first_name }}</p>
    <p>Email : {{ user.email }}</p>
    <p>Promotion INSA  : {{ wu_user.promo }} </p>
    <p>Ville  : {{ wu_user.city }} </p>
    <p>Possibilité d'accueillur des WUs : {{ wu_user.can_welcome_people }} </p>

    <p><a class="btn btn-primary" href="{% url 'users:update_profile' %}">Mettre à jour mes informations</a></p>
    <p><a class="btn btn-default" href="{% url 'main:main_panel' %}">Retour au menu</a></p>
</form>

{% endblock content %}

wu/templates/wu/profile_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
        <p>This will be the place to put the form for user profile update.</p>
</body>
</html>

wu/templates/wu/register.html
{% extends 'base.html' %}
{% block content %}

    {% if not user.is_authenticated %}
        <strong>S'enregistrer sur WUP</strong>

        {% if registered %}
        <strong>Thank you for registering!</strong>
        <a href="/">Se connecter</a><br />
        {% else %}
            <form role="form" class="user_form" method="post" action="/users/register/"
                    enctype="multipart/form-data">

                {% csrf_token %}

                <!-- Display each form. The as_p method wraps each element in a paragraph
                     (<p>) element. This ensures each element appears on a new line,
                     making everything look neater. -->
                     <div class="row">
                        <div class="col-lg-4 formulaire-part">
                         {{ user_form.as_p }}
                        </div>
                        <div class="col-lg-4 formulaire-part">
                         {{ profile_form.as_p }}
                        </div>

                    </div>

                <!-- Provide a button to click to submit the form. -->
                <input class="btn  btn-primary btn-lg" type="submit" name="submit" value="Register" />
                <a href="javascript:history.go(-1)"><button type="button" class="btn btn-default">Retour</button></a>
            </form>
        {% endif %}


    {% else %}
        <strong>Vous êtes déjà connecté</strong>
    {% endif %}

{% endblock content %}

wu/templates/wu/wu_detail.html
{% extends 'base.html' %}

{% block content %}

    <h1>{{ user.username }}</h1>
    <p>{{ wu_user.promo }}</p>
    <p>{{ wu_user.city }}</p>

    <!-- Ajouter un champ pour envoyer directement un message à ce contact (mail, puis à l'avenir, telegram, skype...)-->
    <p><a href="{% url 'users:user_list' %}">Retour à la liste</a></p>

{% endblock %}

wu/templates/wu/wu_list.html
{% extends 'base.html' %}

{% block content %}
<strong>Membre de la Famille</string>
    <div class="family-memebers">
    {% for user, wu_user in all_users %}
        <div class="col-lg-4 " >
            <div class="sub-content"><p>
            	<table>
            		<tr>
		            	<td><img class="publication-header-logo " src="{{ wu_user.image.url }}"></td>
		            	<td><a href="{% url 'users:user_detail' wu_user.user.pk %}">{{ wu_user.user.username }}</a></p></td>
		            	<td><p>{{wu_user.promo}}</p></td>
	            	</tr>
            	</table>
        	</div>
        </div>
    {% endfor %}
	</div>
    <p><a class="btn btn-default" href="{% url 'main:main_panel' %}">Retour au menu</a></p>

{% endblock content %}