dashboard/urls.py
from django.conf.urls import patterns, url, include
from . import views

urlpatterns = patterns('',
    url(r'^$', views.main_panel, name='main_panel'),
    url(r'^notifications/$', views.notifications, name='notifications'),
    url(r'^notifications/(?P<pk>\d+)/$', views.notification_link, name='notification_link'),
    )

travel/urls.py
from django.conf.urls import patterns, url
from . import views

urlpatterns = patterns('',
    url(r'^$', views.travel_list, name='travel_list'),
    url(r'^(?P<pk>\d+)/$', views.travel_detail, name='travel_detail'),

    url(r'^(?P<pk>\d+)/subscribe$', views.travel_subscribe, name='travel_subscribe'),
    url(r'^(?P<pk>\d+)/unsubscribe$', views.travel_unsubscribe, name='travel_unsubscribe'),
    url(r'^mytravels/$', views.my_travels, name='my_travels'),
    url(r'^mycreatedtravels/$', views.my_created_travels, name='my_created_travels'),
    url(r'^create/$', views.create_travel, name='create_travel')
)

wu/urls.py
from django.conf.urls import patterns, url
from . import views

urlpatterns = patterns('',
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^profile/$', views.user_profile, name='profile'),
    url(r'^update_profile/$', views.user_profile_update, name='update_profile'),
    url(r'^family/$', views.user_list, name='user_list'),
    url(r'^family/(?P<pk>\d+)/$', views.user_detail, name='user_detail'),
)

wup/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^$', 'wu.views.index'),
    url(r'^index.html$', 'wu.views.index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('wu.urls', namespace='users')),
    url(r'^dashboard/', include('dashboard.urls', namespace='main')),
    url(r'^travel/', include('travel.urls', namespace='travel')),
]

#autorisaton to access static and media file. In prod environement this may be changed by http server rules 
urlpatterns += [
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.STATIC_ROOT,
    })]

dashboard/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils import timezone
from django.core.validators import MaxValueValidator


#This fonctions is normally called by a daemon
# but for demonstration it will be run for each creation of facts
def compute():
	facts = Historique.objects.filter(notified=False)
	for fact in facts:
		if fact.action_type == 'TC':
			newFlow = Flow(fact=fact)
			newFlow.save()
		if fact.action_type == 'TS':
			newFlow = Flow(fact=fact)
			newFlow.save()
			newNotification = Notification(fact=fact, receiver=fact.object_travel.author, message="Un membre a rejoin votre voyage")
			newNotification.save()
		if fact.action_type == 'TU':
			newFlow = Flow(fact=fact)
			newFlow.save()
			newNotification = Notification(fact=fact, receiver=fact.object_travel.author, message="Un membre a quitté votre voyage")
			newNotification.save()

		if fact.action_type == 'UJ':
			newFlow = Flow(fact=fact)
			newFlow.save()
			newNotification = Notification(fact=fact, message="Un nouveau membre a rejoin la famille. Accueillons le comme il faut!")
			newNotification.save()


		fact.notified = True
		fact.save()




class Historique(models.Model):
	ACTION_CHOICES=(
			('WUPN','WupNews'),
			('UJ','UserJoined'),
			('TS','TravelSubscribe'),
			('TU','TravelUnsubscribe'),
			('TC','TravelCreated'),
			('TCMT','TravelCommented'),
			('TCC','TravelCanceled'),

			# add new actions
		)
	OBJECT_TYPES=(
			('N','None'),
			('TR','Travel'),
			('U','User'),  # object is actor
		)
	action_type = models.CharField(max_length=4, choices=ACTION_CHOICES, default='WUPN')
	actor = models.ForeignKey('wu.WuProfil', null=True)
	date = models.DateTimeField(default=timezone.now)
	notified = models.BooleanField(default=False)
	object_type = models.CharField(max_length=2, choices=OBJECT_TYPES, default='N')
	object_travel = models.ForeignKey('travel.Travel', null=True)
	message = models.CharField(max_length=200, null=True)

	# add new objects (group, comment etc.. referencing the object as foreign key)

	def newTravelFact(actor, action_type, object_travel):
		historique = Historique(
		    actor=actor,
		    action_type=action_type,
		    object_type='TR',
		    object_travel=object_travel
		    )
		historique.save()
		compute()

	def newUserFact(actor, action_type, object_user):
		historique = Historique(
		    actor=actor,
		    action_type=action_type,
		    object_type='U'
		    )
		historique.save()
		compute()

	def news(message):
		historique = Historique(
		    message=message
		    )
		historique.save()

		compute()


class Notification(models.Model):
	receiver = models.ForeignKey('wu.WuProfil', null=True)
	message = models.CharField(max_length=200)
	link = models.CharField(max_length=200)
	seen = models.BooleanField(default=False)
	fact = models.ForeignKey('Historique')

class Flow(models.Model):
	#receiver = null => concerns all members
	receiver = models.ForeignKey('wu.WuProfil', null=True)
	fact = models.ForeignKey('Historique')

dashboard/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from .models import Historique, Flow, Notification


@login_required
def main_panel(request):
    return render(request, 'dashboard/dashboard.html', 
		{
			"title":"Bienvenue","historique":Flow.objects.filter(Q(receiver__user__id=request.user.id)| Q(receiver__isnull=True)).order_by('-fact__date')
		}
	)
@login_required
def notifications(request):
	return render(request, 'dashboard/notifications.html', 
		{
			"title":"Vos Notifications","notifications":Notification.objects.filter(Q(receiver__user__id=request.user.id)| Q(receiver__isnull=True)).order_by('-id')
		}
	)

@login_required
def notification_link(request, pk):
	notif = get_object_or_404(Notification, pk=pk)
	notif.seen = True
	notif.save()
	return render(request, 'dashboard/dashboard.html', 
		{
			"historique":Flow.objects.filter(fact__id=notif.fact.id)
		}
	)

dashboard/templates/dashboard/dashboard.html
{% extends 'base.html' %}


{% block content %}



<div class="container">
      
        <div class="starter-template">

        <h1>{{ title }}</h1>

       <div class="publication row">
      
       {% for item in historique %}
         {% if item.fact.object_type == 'TR' %}
              <div class="col-lg-8">
                  <div class="row publication-header">
                    <table>
                      <tr>
                        <td>
                          <img class="publication-header-logo " src="{{ item.fact.actor.image.url }}"/>
                        </td>
                          {% if item.fact.action_type == 'TC' %}
                            <img class="publication-header-symbole" src="/static/images/TC.png" />
                          {% elif item.fact.action_type == 'TS' %}
                            <img class="publication-header-symbole" src="/static/images/TS.png" />
                          {% elif item.fact.action_type == 'TU' %}
                            <img class="publication-header-symbole" src="/static/images/TU.png" />
                          {% endif %}
                        <td> 
                          <div class="publication-header-announce "><b>{{ item.fact.actor.user.username }} 
                          {% if item.fact.action_type == 'TC' %}
                            propose un nouveau 
                          {% elif item.fact.action_type == 'TS' %}
                            participe à ce 
                          {% elif item.fact.action_type == 'TU' %}
                            ne participe plus  à ce 
                          {% endif %}
                          <a href="/travel/{{ item.fact.object_travel.id }}">voyage</a></b> <br/> le {{ item.fact.date }}</div>

                        </td>
                      </tr>
                    </table>
                  </div>
                    <div class="row publication-content">
                          <div class="publication-content-title"> <h4>{{ item.fact.object_travel.title }}</h4></div> 
                        
                          <img class="publication-content-image"  src="{{item.fact.object_travel.image.url }}" />                       
                          <p class="publication-content-text"> {{ item.fact.object_travel.description }}</p>
                        
                  </div>
              </div>
            {% elif item.fact.object_type == 'N' %}
                 <div class="col-lg-8">
                      <div class="row publication-header">
                        <table>
                          <tr>
                            <td>
                              <img class="publication-header-logo " src="/static/images/news.png">
                            </td>
                            <td>
                              <div class="publication-header-announce "><b>News</b></br> Publié le {{ item.fact.date }}</div><!---->
                            </td>
                          </tr>
                        </table>
                      </div>

                      <div class="row publication-content">                        
                        <div> 
                          <p class="publication-content-text"> {{ item.fact.message }}</p>
                         </div>
                      </div>
                    </div>
              {% elif item.fact.object_type == 'U' %}
                 <div class="col-lg-8">
                      <div class="row publication-header">
                        <table>
                          <tr>
                            <td>
                              <img class="publication-header-logo " src="{{ item.fact.actor.image.url }}"/>
                            </td>
                             <img class="publication-header-symbole" src="/static/images/UJ.png">
                            <td>
                              <div class="publication-header-announce "> Ce <a href="#">membre</a> a rejoin la communauté </div><!---->
                            </td>
                          </tr>
                        </table>
                      </div>
                    </div>
             {% endif %}
           {% endfor %}
        </div>
      </div>
</div><!-- /.container -->


{% endblock content %}

dashboard/templates/dashboard/dashboard_bak.html
{% extends 'base.html' %}


{% block content %}


<div class="container">
      
        <h1>Bienvenue</h1>

          <div class="action row">
                <div class="col-sm-4">
                        <a href="{% url 'travel:create_travel' %}"  class="dashboard-action-button btn btn-medium btn-primary"></i> Créer un voyage</a></br>
                </div>
                <div class="col-sm-4">
                       <div class="dashboard-action-text">
                         Créer un évenement visible par toute la famille
                       </div> 
               </div>
          </div>
           <div class="action row">
                <div class="col-sm-4">
                        <a href="{% url 'travel:travel_list' %}" class="dashboard-action-button btn btn-medium btn-primary"></i> Consulter les voyages</a></br>
                </div>
                <div class="col-sm-4">
                       <div class="dashboard-action-text">
                         Consulter les voyages
                       </div> 
               </div>
          </div>
         <div class="action row">
                <div class="col-sm-4">
                        <a href="{% url 'users:user_list' %}" class="dashboard-action-button btn btn-medium btn-primary"></i> Les membres de la famille</a></br>
                </div>
                <div class="col-sm-4">
                       <div class="dashboard-action-text">
                         Liste des membres
                       </div>
               </div>
          </div>
         <div class="action row">
                <div class="col-sm-4">
                        <a href="{% url 'users:profile' %}" class="dashboard-action-button btn btn-medium btn-primary"></i> Mon Profil</a></br>
                </div>
                <div class="col-sm-4">
                       <div class="dashboard-action-text">
                         (et modification des informations personnelles)
                       </div>
               </div>
          </div>
</div><!-- /.container -->


{% endblock content %}

dashboard/templates/dashboard/fact.html
{% extends 'base.html' %}

{% block content %}

    <h1>Main page</h1>
    <p><a href="{% url 'travel:travel_list' %}">Voyages</a></p>
    <p><a href="{% url 'users:user_list' %}">La famille</a></p>
    <p><a href="{% url 'users:profile' %}">Mon profil</a></p>
    <p><a href="{% url 'users:logout' %}">Déconnexion</a></p>

{% endblock %}

dashboard/templates/dashboard/index.html
<<!-- deprecated -->

{% extends 'base.html' %}

{% block content %}

    <h1>Main page</h1>
    <p><a href="{% url 'travel:travel_list' %}">Voyages</a></p>
    <p><a href="{% url 'users:user_list' %}">La famille</a></p>
    <p><a href="{% url 'users:profile' %}">Mon profil</a></p>
    <p><a href="{% url 'users:logout' %}">Déconnexion</a></p>

{% endblock %}

dashboard/templates/dashboard/notifications.html
{% extends 'base.html' %}

{% block content %}

    
<div class="container">
      
        <h1>Notifications</h1>

        <div class="starter-template">
       <div class="publication row">
      
       {% for notif in notifications %}

         {% if notif.fact.object_type == 'TR' %}
              <div class="col-lg-8 {% if not notif.seen %} notif_unread {% endif %}">
              	<a href="/dashboard/notifications/{{ notif.id }}">
                  <div class="row publication-header">
                    <table>
                      <tr>
                        <td>
                          <img class="publication-header-logo " src="{{ notif.fact.actor.image.url }}"/>
                        </td>
                          {% if notif.fact.action_type == 'TC' %}
                            <img class="publication-header-symbole" src="/static/images/TC.png" />
                          {% elif notif.fact.action_type == 'TS' %}
                            <img class="publication-header-symbole" src="/static/images/TS.png" />
                          {% elif notif.fact.action_type == 'TU' %}
                            <img class="publication-header-symbole" src="/static/images/TU.png" />
                          {% endif %}
                        <td> 
                          <div class="publication-header-announce ">  {{ notif.message }}</div>

                        </td>
                      </tr>
                    </table></a>
                  </div>
              </div>
            {% elif notif.fact.object_type == 'N' %}
                 <div class="col-lg-8">
                      <div class="row publication-header">
                        <table>
                          <tr>
                            <td>
                              <img class="publication-header-logo " src="/static/images/news.png">
                            </td>
                            <td>
                              <div class="publication-header-announce "><b>News</b></br> Publié le {{ notif.fact.date }}</div><!---->
                            </td>
                          </tr>
                        </table>
                      </div>
                    </div>
           {% elif notif.fact.object_type == 'U' %}
                 <div class="col-lg-8">
                      <div class="row publication-header">
                        <table>
                          <tr>
                            <td>
                          		<img class="publication-header-logo " src="{{ notif.fact.actor.image.url }}"/>
                            </td>
                             <img class="publication-header-symbole" src="/static/images/UJ.png">
                            <td>
                              <div class="publication-header-announce "> {{ notif.message }} </div><!---->
                            </td>
                          </tr>
                        </table>
                      </div>
                    </div>
             {% endif %}
           {% endfor %}
        </div>
      </div>
</div><!-- /.container -->

{% endblock %}