dashboard/urls.py
from django.conf.urls import patterns, url, include
from . import views

urlpatterns = patterns('',
    url(r'^$', views.main_panel, name='main_panel'),
    url(r'^notifications/$', views.notifications, name='notifications'),
    url(r'^notifications/(?P<pk>\d+)/$', views.notification_link, name='notification_link'),
    )

travel/urls.py
from django.conf.urls import patterns, url
from . import views

urlpatterns = patterns('',
    url(r'^$', views.travel_list, name='travel_list'),
    url(r'^(?P<pk>\d+)/$', views.travel_detail, name='travel_detail'),

    url(r'^(?P<pk>\d+)/subscribe$', views.travel_subscribe, name='travel_subscribe'),
    url(r'^(?P<pk>\d+)/unsubscribe$', views.travel_unsubscribe, name='travel_unsubscribe'),
    url(r'^mytravels/$', views.my_travels, name='my_travels'),
    url(r'^mycreatedtravels/$', views.my_created_travels, name='my_created_travels'),
    url(r'^create/$', views.create_travel, name='create_travel')
)

wu/urls.py
from django.conf.urls import patterns, url
from . import views

urlpatterns = patterns('',
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^profile/$', views.user_profile, name='profile'),
    url(r'^update_profile/$', views.user_profile_update, name='update_profile'),
    url(r'^family/$', views.user_list, name='user_list'),
    url(r'^family/(?P<pk>\d+)/$', views.user_detail, name='user_detail'),
)

wup/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^$', 'wu.views.index'),
    url(r'^index.html$', 'wu.views.index'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('wu.urls', namespace='users')),
    url(r'^dashboard/', include('dashboard.urls', namespace='main')),
    url(r'^travel/', include('travel.urls', namespace='travel')),
]

#autorisaton to access static and media file. In prod environement this may be changed by http server rules 
urlpatterns += [
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT,
    }),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.STATIC_ROOT,
    })]

templates/base.html
{% load staticfiles %}
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>WUP</title>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css">
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
        <link href="{% static 'css/global.css' %}" rel="stylesheet">
        <link href="{% static 'css/login.css' %}" rel="stylesheet">
    </head>

    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                {% if has_notifs %}
                 <i class="glyphicon glyphicon-certificate" style="color:#00FF00"></i>
                {% elif not has_notifs %}
                <span class="icon-bar"></span>
                {% endif %}
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'main:main_panel'%}"><b>What's Up Paradise</b></a>
            </div>

            <div id="navbar" class="collapse navbar-collapse">
              <ul class="nav navbar-nav">
                <li><a href="{% url 'main:main_panel'%}">Dashboard</a></li>
                <li><a href="{% url 'travel:travel_list'%}">Voyages</a></li>
              </ul>
               <ul class="nav navbar-nav navbar-right">
               {% if not user.is_authenticated %}
                <li><a href="{% url 'users:login'%}">Se connecter</a></li>
               {% endif %}

               {% if user.is_authenticated %}
               <li class="nav-divider"></li>
               <!--<li><a  id="notif_count" {% if has_notifs %} style="color:#00FF00"{% endif %} href='#'><b>{{ notif_count }}</b></a></li>-->
                <li>
                  <!--<a href="{% url 'users:profile'%}"></a>-->
                  
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                    <img id = "menu_profile_image" src="{{ user.wuprofil.image.url }}"/><b>{{ user.username }}{% if has_notifs %}<sup id="notif_count"  style="color:#00FF00" href='#'><b>{{ notif_count }}</b></sup>{% endif %}</b>
                  </a>
                  <ul class="dropdown-menu">
                    <li><a href="{% url 'users:profile'%}">Mon profile</a></li>
                    <li><a {% if has_notifs %} style="color:#00EE00"{% endif %}  href="{% url 'main:notifications'%}">Notifications</a></li>
                  </ul>
                </li>

                  
                <li><a href="{% url 'users:logout'%}">Se déconnecter</a></li>
               </ul>
               {% endif %}

            </div><!--/.nav-collapse -->

          </div>

        </div>
        {% block content %}

        {% endblock %}


    </body>
</html>